
services:

  postgres-01:
    image: "postgres:15-alpine"
    hostname: "postgres-01"
    container_name: "postgres-01"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "media"
      PGUSER: "postgres"
    volumes:
      - "postgres01_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: "always"

volumes:
  postgres01_data:
    

  
