
services:

  postgres-01:
    image: "postgres:15-alpine"
    hostname: "postgres-01"
    container_name: "postgres-01"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "media"
      PGUSER: "postgres"
    volumes:
      - "postgres01_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: "always"

#  Default credentials minioadmin:minioadmin
  s3-01:
    image: "quay.io/minio/minio:RELEASE.2023-06-23T20-26-00Z"
    hostname: "s3-01"
    container_name: "s3-01"
    ports:
      - "9001:9001"
      - "9000:9000"
    command: "server /data --console-address \":9001\""
    restart: "always"
    healthcheck:
      test: "curl --silent --fail http://localhost:9001 || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "s3-01_data:/data"

volumes:
  postgres01_data:
  s3-01_data:
