package io.github.akmal2409;

import io.github.akmal2409.hls.CommonPlaylistTags;
import io.github.akmal2409.hls.tag.Tag;
import io.github.akmal2409.hls.tag.TagValue.SingleTagValue;

public final class PlaylistUtils {

  private PlaylistUtils() {
    throw new IllegalStateException("Cannot instantiate a utility class");
  }

  public static void writeCommonHeader(StringBuilder sb, Integer version) {
    sb.append(Tag.fromKey(CommonPlaylistTags.PLAYLIST_HEADER).serialise());
    sb.append("\n\n\n");

    sb.append("##########################################################################\n");
    sb.append("# This playlist has been auto generated by the segment-packager library  #\n");
    sb.append("# Do not modify this file directly                                        #\n");
    sb.append("##########################################################################\n\n\n");

    if (version != null) {
      sb.append(Tag.fromKV(CommonPlaylistTags.VERSION,
          new SingleTagValue(String.valueOf(version))).serialise());
      sb.append("\n");
    }
  }
}
