server:
  port: 8080


spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/media"
    username: "postgres"
    password: "postgres"
  jpa:
    show-sql: true


app:
  media-upload:
    pre-signed-url-validity: "2h"
  media-s3:
    host: "http://localhost:9000"
