name: media-service-ci
run-name: ${{ github.actor }} triggered CI pipeline for media service
on:
  push:
    branches:
      - main
      - 'releases/**'
    paths: ['media/**']

jobs: 
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./media
    steps:
      - name: 'Repository checkout'
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github
            media

      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3 
        with: 
          java-version: 17
          distribution: 'corretto'
          cache: 'maven'
      - name: 'Unit tests'
        run: mvn test
      - name: 'Integration tests'
        run: mvn failsafe:integration-test failsafe:verify
      - name: 'Packaging'
        run: mvn package -DskipTests=true


